name: Tests
run-name: Tests on ${{ github.ref_name }}

on:
  push:
    paths-include:
      - '**.lua'
      - '.github/workflows/test.yml'
  pull_request:
    paths-include:
      - '**.lua'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  ci_tests:
    name: CI Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup just runner
        uses: extractions/setup-just@v2

      - name: Install latest yazi
        run: |
          curl -L \
            https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-unknown-linux-gnu.zip \
            -o yazi.zip
          unzip -q yazi.zip -d yazi-tmp
          sudo mv yazi-tmp/*/{yazi,ya} /usr/local/bin/
          sudo chmod +x /usr/local/bin/yazi /usr/local/bin/ya
          rm -rf yazi.zip yazi-tmp
      - name: Check Yazi
        run: yazi --version

      - name: Install clipboard and xvfb
        run: sudo apt-get update && sudo apt-get install -y xclip xvfb

      - name: Run tests
        run: just test
        working-directory: tests
